version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  post_build:
    commands:
      - curl -k -u ${FITOXSUID}:${FITOXSTOKEN} --request POST -H "Content-Type:application/json" -d '{\"pit\":\"310\",\"targetid\":\"UKwkxspv3Q5FNfS60ftQ1619052131\",\"ci\":\"awscodestar\",\"tipo\":\"3\"}' https://fitoxs.com/ScanTarget/
      
