version: 0.2

phases:
  build:
    commands:
      - curl -k -u $FITOXSUID:$FITOXSTOKEN --request POST -H "Content-Type:application/json" -d '{"pit":"310","targetid":"tBfO6QkSfg5hZNDg50jG1619129611","ci":"Circle CI","tipo":"6"}' https://fitoxs.com/ScanTarget/

     
